#!/bin/bash

jp () {
  local path="$1"
  local dirname=$(dirname "$path")
  local basename=$(basename "$path")
  local class=${basename%%.class}
  # perl to replace tabs by spaces
  ( cd "$dirname" && javap -c -s -private $class | perl -pe 's/\t/  /g' > "$class".javap )
}

echo $1
jp $1
