#!/bin/bash

files="$@"

for f in $files; do
  path="$1"
  dirname=$(dirname "$path")
  basename=$(basename "$path")
  class=${basename%%.class}
  # perl to replace tabs by spaces
  ( cd "$dirname" && javap -v $class | perl -pe 's/\t/  /g' > "$class".javap )
done
